apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deploy
  labels:
   {{- include "ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
     {{- include "ui.labels" . | nindent 8 }}
    spec:
      containers:
        - name: todoapp
          image: {{ .Values.app.image }}
          # resources:
          # {{- toYaml .Values.app.computeres | nindent 12 }}