apiVersion: v1
kind: Service
metadata:
  name: todoApp-service
  labels:
   {{- include "ui.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: todoApp
  type: NodePort