apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  labels:
   {{- include "ui.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30008
  selector:
    app: todoapp
  type: NodePort